export const templates: string[] = [
	"mahkotamu masih dilas, king 👑",
	"giling terus boss 💪",
	"terbaik kandaku 🙌🏼",
	"tipis tipis asal menyala king 👑🔥",
	"makasih sharingnya abangkuhh, tetaplah ilmu padi 🌾🙇‍♂️🌾🔝🔝🔝",
	"lanjutkan abangkuuhh 🔥🔝💥",
	"manyala capt 🔥🔥",
	"kasih paham tipis tipis 🤝🏼",
	"top selalu idola 🔥",
	"idola 🙌🏼🙌🏼",
	"tetap membumi abangkuh 🔥🙌🏼🌎",
	"sesekali 🙌🏼",
	"kalau diatas jgn lupa merunduk 🌾🙌🏼🙇‍♂️",
	"eh yg punya setengah indo nih ee 😜😜",
	"eitsss pondasi bangsa abangkuuhh 🔥🔝🙌🏼",
	"kelas abangda 🔥🫡",
	"kasih jedag jedug dulu abangkuh🤩🥵",
	"jangan kasi longgar king 🔝💯🔥🙌🏼",
	"wanita mana yang berani menyakitimu king 💯💯💪❤‍🔥",
	"kelas banget kanda 🙏🏼🕺🏻",
	"panutan 🔝✊🏼🙌🏼",
	"top abangku 👍🏼👍🏼",
	"percaya proses capt 🔥🔥",
	"manyala ilmu padi 🌾🔥",
	"kelas abangkuu 🔥🔝",
	"🔛🔝 selalu idola 🔥",
	"ini mahkotamu king 👑",
	"trcium aroma ilmu padi abangkuh🔥🔥🌾🌾",
	"jangan kasih kendor ee 🕺🏻🕺🏻",
	"apotik tutup captain 🔥🔥💯🔝",
	"kasih paham capt 🔥💯🙌🏼",
	"percaya proses king 💯💯💪❤‍🔥",
	"izin abangkuu 🔥",
	"mahkota sedang transit di dc cakung kingg 🔥👑🙇‍♂️",
	"tipis tipis 🔥🔛🔝",
	"rispeekk 👍🏼🙌🏼",
	"kasih keras idola 🔥🔥",
	"kasih keras abangkuhh 🔥👊🏼",
	"kelas boskuuuh 🔥👍🏼",
	"capt idolaa 🔥🙌🏼🔝",
	"weees kelas abangku 🔥🔥",
	"tetep ilmu padi 🌾🌾",
	"terstill💪💪",
	"abang idola panutan ini 😘😘",
	"top 🔝",
	"meroket abangku 🚀🚀🚀",
	"starboy vibez🥵😎🥀💥🐙",
	"gas kanda 🔥🔥",
	"isinya daging semua abangkuu🔥🔥🔛🔝",
	"jagoan mama muncul 🔥🔥🔥",
	"beraksi🍻🍻",
	"kasih apa? kasih paham abangkuhh👊👊👊🔥🔥🔥🔥",
	"kasih paham queen, ilmu baddie 🔥🔥💅💅",
	"kasih paham queen 🤭🔥 MENYALA",
	"manyala panutan abangda 🔥🔥",
	"kasih tebal king 🤙🤙",
	"kasih tahu abangkuuu🔥🔥🙇‍♂️🙇‍♂️",
	"sungkem dulu abangkuuu🙇‍♂️🙇‍♂️",
	"biarkan abangku memasakkk🔥🔥🧑‍🍳🧑‍🍳",
	"kasi paham wakk 🔥🔥🔥",
	"eihhh mantaapp pedii kaliii 🔥🔥🔥",
	"bertahap abangkuuuu🔥🤙🪜👟",
	"nikmati proses kakandaaa🤙🔥🙇‍♂️",
	"jangan kasih kendor king 🔥🔥🔥",
];

export const templatesEn: string[] = [
	"your crown is still welded, king",
	"keep grinding boss 💪",
	"U're the best bro 🙌🏼",
	"thin thin origin light king 👑🔥",
	"Thanks for sharing, brother, still rice science 🌾🙇‍♂️🌾🔝🔝🔝",
	"keep going my brother 🔥🔝💥",
	"fire capt 🔥🔥",
	"Give me a little understanding 🤝🏼",
	"top is always an idol 🔥",
	"idol 🙌🏼🙌🏼",
	"stay grounded bro 🔥🙌🏼🌎",
	"occasionally 🙌🏼",
	"If you're at the top, don't forget to duck 🌾🙌🏼🙇‍♂️",
	"Hey, the one who has half Indonesian, ee 😜😜",
	"eitsss the foundation of the nation my brother 🔥🔝🙌🏼",
	"brother class 🔥🫡",
	"Give me a break first, dear brother🤩🥵",
	"don't give it a loose king 🔝💯🔥🙌🏼",
	"Which woman dares to hurt you King 💯💯💪❤‍🔥",
	"really class bro 🙏🏼🕺🏻",
	"role model 🔝✊🏼🙌🏼",
	"top my brother 👍🏼👍🏼",
	"trust the process capt 🔥🔥",
	"nyala rice science 🌾🔥",
	"my brother's class 🔥🔝",
	"🔛🔝 always an idol 🔥",
	"this is your crown king 👑",
	"I can smell the aroma of my brother's rice knowledge🔥🔥🌾🌾",
	"don't give me slack ee 🕺🏻🕺🏻",
	"pharmacy closed captain 🔥🔥💯🔝",
	"Tell me to understand Capt 🔥💯🙌🏼",
	"trust the process king 💯💯💪❤‍🔥",
	"my brother's permission 🔥",
	"the crown is in transit at DC Cakung Kingg 🔥👑🙇‍♂️",
	"thin thin 🔥🔛🔝",
	"rispeekk 👍🏼🙌🏼",
	"love your idol hard 🔥🔥",
	"Love you hard, brother 🔥👊🏼",
	"class myboss 🔥👍🏼",
	"capt idola 🔥🙌🏼🔝",
	"weees my brother's class 🔥🔥",
	"still rice science 🌾🌾",
	"terstill💪💪",
	"This role model idol brother 😘😘",
	"top 🔝",
	"skyrocketing my brother 🚀🚀🚀",
	"starboy vibez🥵😎🥀💥🐙",
	"speeding kanda 🔥🔥",
	"give tofu my brotherrr🔥🔥🙇‍♂️🙇‍♂️",
	"let my brotherrr cook🔥🔥🧑‍🍳🧑‍🍳",
	"step by step my brotherrr🔥🤙🪜👟",
	"enjoy the process my dear brotherrr🤙🔥🙇‍♂️"
];
