export const templates: string[] = [
  "top 🔝",
  "terstill💪💪",
  "sesekali 🙌🏼",
  "gas kanda 🔥🔥",
  "idola 🙌🏼🙌🏼",
  "izin abangkuu 🔥",
  "manyala capt 🔥🔥",
  "panutan 🔝✊🏼🙌🏼",
  "rispeekk 👍🏼🙌🏼",
  "kelas abangda 🔥🫡",
  "tipis tipis 🔥🔛🔝",
  "kelas abangkuu 🔥🔝",
  "top selalu idola 🔥",
  "🔛🔝 selalu idola 🔥",
  "capt idolaa 🔥🙌🏼🔝",
  "tetep ilmu padi 🌾🌾",
  "top abangku 👍🏼👍🏼",
  "ini mahkotamu king 👑",
  "kelas boskuuuh 🔥👍🏼",
  "kasih keras idola 🔥🔥",
  "manyala ilmu padi 🌾🔥",
  "meroket abangku 🚀🚀🚀",
  "starboy vibez🥵😎🥀💥🐙",
  "percaya proses capt 🔥🔥",
  "weees kelas abangku 🔥🔥",
  "kasih paham capt 🔥💯🙌🏼",
  "kelas banget kanda 🙏🏼🕺🏻",
  "lanjutkan abangkuuhh 🔥🔝💥",
  "abang idola panutan ini 😘😘",
  "kasih keras abangkuhh 🔥👊🏼",
  "kasih paham tipis tipis 🤝🏼",
  "apotik tutup captain 🔥🔥💯🔝",
  "percaya proses king 💯💯💪❤‍🔥",
  "jangan kasih kendor ee 🕺🏻🕺🏻",
  "tetap membumi abangkuh 🔥🙌🏼🌎",
  "tipis tipis asal menyala king 👑🔥",
  "jangan kasi longgar king 🔝💯🔥🙌🏼",
  "kasih jedag jedug dulu abangkuh🤩🥵",
  "eh yg punya setengah indo nih ee 😜😜",
  "trcium aroma ilmu padi abangkuh🔥🔥🌾🌾",
  "eitsss pondasi bangsa abangkuuhh 🔥🔝🙌🏼",
  "kalau diatas jgn lupa merunduk 🌾🙌🏼🙇‍♂️",
  "mahkota sedang transit di dc cakung kingg 🔥👑🙇‍♂️",
  "wanita mana yang berani menyakitimu king 💯💯💪❤‍🔥",
  "makasih sharingnya abangkuhh, tetaplah ilmu padi 🌾🙇‍♂️🌾🔝🔝🔝",

  // langsung tambah di bawah ini 🔥🔥🔥
];
